### ISSUE TITLE
Tracking navigations in a single page app (SPA) with swetrix and react

### ISSUE THREAD

**Issue by joepio** [Swetrix/swetrix-js#9]
Hi there! Thanks for doing everything open source :)

I'm currently working on a react project, a [search app](https://github.com/ontola/openbesluitvorming/issues/144), where i use a query parameter to store the search query state. I want to track these queries using swetrix. I'm successfully tracking the initial page load now, but subsequent navigations seem to be ignored. With alternatives (piwik / matomo / google analytics) I just added the JS tracking script and they tracked the history / navigation events. 

Does Swetrix not handle SPA navigations by default? I searched for the docs for some option, but didn't find it. Could you help out on how I could achieve this?

**Comment by kruzhambus** [comment]
> Hi there! Thanks for doing everything open source :)
> 
> 
> 
> I'm currently working on a react project, a [search app](https://github.com/ontola/openbesluitvorming/issues/144), where i use a query parameter to store the search query state. I want to track these queries using swetrix. I'm successfully tracking the initial page load now, but subsequent navigations seem to be ignored. With alternatives (piwik / matomo / google analytics) I just added the JS tracking script and they tracked the history / navigation events. 
> 
> 
> 
> Does Swetrix not handle SPA navigations by default? I searched for the docs for some option, but didn't find it. Could you help out on how I could achieve this?

Hey @joepio, thanks for using Swetrix. This is something that we prepared but did not add in past as there was no demand for it (currently we track the pathname changes).

We'll add support for queries / hash based routing to trigger page views today and let you know when it's done.

**Comment by joepio** [comment]
Whoa, top notch support :)

**Comment by Blaumaus** [comment]
Hey @joepio, we released support for `hash` and `search` based routing in [v2.4.0](https://github.com/Swetrix/swetrix-js/releases/tag/v2.4.0).
Take a look at the documentation on how to enable it: https://docs.swetrix.com/swetrix-js-reference#trackviews

In short, on your search app you should simply add a new parameter `search: true` to the `trackViews` function call and it will work out of the box.

I.e.
```javascript
swetrix.trackViews({
  // ... other parameters
  search: true,
})
```

Let me know if this works for you and if you have any other question.
